name: DevOps Python Pipeline

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/python-devops-app
  K8S_NAMESPACE: production

jobs:
  quality-assurance:
    name: Python QA & Security (SAST)
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v4.2.2
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0 

      # actions/setup-python@v5.3.0
      - name: Set up Python
        uses: actions/setup-python@0b93645e9ee717584548a7f451408d36005a2010
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests with Coverage
        run: |
          pytest --cov=src --cov-report=xml src/

      # SonarSource/sonarqube-scan-action@v5.0.0
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@0302636ef4ca53986687352378943f779770e7e1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
            -Dsonar.python.version=3.12
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=src/

  build-and-scan:
    name: Docker Build & Scan
    needs: quality-assurance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      # docker/setup-buildx-action@v3.8.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5

      # docker/build-push-action@v6.10.0
      - name: Build Image
        uses: docker/build-push-action@ca857db2dca51ec3022c34d4967396a84920264b
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          load: true 

      - name: Container Scan (Trivy)
        uses: aquasecurity/trivy-action@18f251a8b2671da53f16cf3ba02344912d7d03a2
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  deploy:
    name: Deploy to Local K8s
    needs: build-and-scan
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted 
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Deploy
        shell: pwsh
        run: |
          kubectl apply -f k8s/deployment.yaml -n ${{ env.K8S_NAMESPACE }}