name: DevOps Python Pipeline

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/python-devops-app
  K8S_NAMESPACE: production

jobs:
  code-quality-sast:  # quality-assurance:
    name: Code Quality & Security (SAST)  # Python QA & Security (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests with Coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          python -m pytest --cov=src --cov-report=xml:coverage.xml tests/

      - name: Check environment variables
        run: |
              echo "SONAR_PROJECT_KEY=$SONAR_PROJECT_KEY"
              echo "SONAR_ORG_KEY=$SONAR_ORG_KEY"

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v6
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
            -Dsonar.python.version=3.12
            -Dsonar.sources=src/
            -Dsonar.tests=tests/
            -Dsonar.test.inclusions=tests/test_app.py
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-image-scan:
    name: Build Image & Scan Vulnerabilities  # Docker Build & Scan
    needs: code-quality-sast
    runs-on: self-hosted
    # optionally tag runner in GitHub Settings
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Start Docker
      #   run: |
      #     net start com.docker.service
      #   continue-on-error: true

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$GITHUB_SHA .

      - name: Run Trivy Scan  # Make sure Trivy is installed on the self-hosted runner
        run: |
            trivy image --exit-code 1 --severity CRITICAL,HIGH $IMAGE_NAME:$GITHUB_SHA

# Cannot deploy on the local self-hosted runner as GitHub cannot reach it
  # deploy:
  #   name: Deploy to Local K8s
  #   needs: build-image-scan
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: self-hosted 
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
  #     - name: Deploy
  #       run: |
  #         kubectl apply -f k8s/deployment.yaml -n $K8S_NAMESPACE
