name: DevOps Python Pipeline

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/python-devops-app
  K8S_NAMESPACE: production

jobs:
  quality-assurance:
    name: Python QA & Security (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests with Coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          python -m pytest --cov=src --cov-report=xml:coverage.xml tests/

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORG_KEY: ${{ secrets.SONAR_ORG_KEY }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
            -Dsonar.python.version=3.12
            -Dsonar.sources=src/
            -Dsonar.tests=tests/
            -Dsonar.test.inclusions=tests/test_app.py
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.verbose=true

  build-and-scan:
    name: Docker Build & Scan
    needs: quality-assurance
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Docker
        shell: cmd
        run: |
          net start com.docker.service

      - name: Build Image
        shell: cmd
        run: |
          docker build --progress=plain -t %IMAGE_NAME%:%GITHUB_SHA% .


      - name: Container Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  deploy:
    name: Deploy to Local K8s
    needs: build-and-scan
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy
        shell: pwsh
        run: |
          kubectl apply -f k8s/deployment.yaml -n ${{ env.K8S_NAMESPACE }}